model = "gpt-5.3-codex"
# model_provider = "anthropic"
model_reasoning_effort = "high"

[projects."/Users/cameron/.dotfiles"]
trust_level = "trusted"

[projects."/Users/cameron/.codex"]
trust_level = "trusted"

[projects."/Users/cameron/repos/daemonize"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

# [model_providers.anthropic]
# name = "Anthropic (OpenAI-compatible)"
# base_url = "https://api.anthropic.com/v1/"
# env_key = "ANTHROPIC_API_KEY"
# wire_api = "responses"
